image: ruby:2.5

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

services:
  - postgres:latest

before_script:
  - apt-get update && apt-get install -y locales nodejs
  - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
  - locale-gen
  - export LC_ALL=en_US.UTF-8
  - RAILS_ENV=test bundle install --jobs $(nproc) --path /cache "${FLAGS[@]}"
  - cp config/gitlab.database.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:schema:load

test:
  script:
    - RAILS_ENV=test bin/rake test

lint:
  script:
    - bundle exec rubocop