# config/app.yml for rails-settings-cached
defaults: &defaults
  tracker_name: "TheCulture.eu"
  tracker_url: "http://localhost:3000"
  announce_interval: 600
  min_interval: 60
  default_peers: 10

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
