# config/app.yml for rails-settings-cached
defaults: &defaults
  tracker_name: "TheCulture.eu"
  tracker_hostname: "tracker.localhost"
  tracker_protocol: "http"
  tracker_port: 3000
  site_hostname: "localhost"
  site_protocol: "http"
  site_port: 3000
  from_email: "please-change-me-at-config-initializers-devise@example.com"
  open_registration: true
  announce_interval: 600
  min_interval: 60
  default_peers: 10
  free_upload: 524288000

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
