# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  sentry_dsn: <%= ENV["SENTRY_DSN"] %>
  skylight_token: <%= ENV["SKYLIGHT_TOKEN"] %>
  from_email: <%= ENV["FROM_EMAIL"] %>
# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ddf81f538675090acf318e42b20713a36a5a3406ebe059b0ca9ac4de6702090f585b09c344e6960dcc48ce375f35ba6ca707c17f8a9399a3a1a3f1e5d14a66d1

test:
  secret_key_base: a80a0cbc52d752bfa3b947a7e487ba03fb962a00ffb0ebc0758733e0e559809934608dbc01d177d6f023a8c30fd8d4a76f0b733d0d5512a5fd2b39fdfeabd74a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
